;***************************************************************
;*******   ASM generated by The FarGray Converter  v0.2.4 ******
;*******   My first animation in assembly langage	  ******
;*******       By mathieu MALATERRE			  ******
;***************************************************************

     include   "doorsos.h"
     include   "graphlib.h"
     include   "fargray.h"
     include   "gray7lib.h"

     xdef _main
     xdef _comment
     xdef _ti89

_main:
	move.w	#2,d3
loop:
	move.w  d3,tours
	jsr     graphlib::clr_scr
	move.w  #$0,-(a7)
	jsr     doorsos::ST_busy
	lea     2(a7),a7

	jsr     gray7lib::on            ; Turn on 7-grayscale
	move.l  gray7lib::plane0,a1     ; Remember plane
	move.l  gray7lib::plane1,a2     ; Remember plane
	lea     planes1(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; Put Picture on Screen !
	jsr     graphlib::clr_scr

	lea     planes2(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; Put Picture on Screen !
	jsr     graphlib::clr_scr

	lea     planes3(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; 
	jsr     graphlib::clr_scr

	lea     planes4(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   
	jsr     graphlib::clr_scr

	lea     planes5(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; 
	jsr     graphlib::clr_scr

	lea     planes6(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; 
	jsr     graphlib::clr_scr

	lea     planes7(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; Put
	jsr     graphlib::clr_scr

	lea     planes8(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; P
	jsr     graphlib::clr_scr

	lea     planes9(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; Put Picture on Sc
	jsr     graphlib::clr_scr

	lea     planes10(pc),a5           ; Set pointer to compressed data !
	move.w  #3120,d7                ; Number of bytes to paint.
	jsr     fargray::put3planepic   ; Put Pic
	jsr     gray7lib::off           ; Turn off Grayscale

	move.w	tours,d3
	dbra	d3,loop
	rts

;****************************************************************
planes1:
	INCBIN	"anim.bin"
planes2:
	INCBIN	"anim1.bin"
planes3:
	INCBIN	"anim2.bin"
planes4:
	INCBIN	"anim3.bin"
planes5:
	INCBIN	"anim4.bin"
planes6:
	INCBIN	"anim5.bin"
planes7:
	INCBIN	"anim6.bin"
planes8:
	INCBIN	"anim7.bin"
planes9:
	INCBIN	"anim8.bin"
planes10:
	INCBIN	"anim9.bin"
tours:	dc.w	0

_comment:
        dc.b "Icky et Scratchy",0

;******************** End of Fargo program **********************

   end